# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ZhDatePicker = ZhDatePicker(self.centralwidget)
        self.ZhDatePicker.setGeometry(QtCore.QRect(330, 360, 240, 30))
        self.ZhDatePicker.setObjectName("ZhDatePicker")
        self.DateEdit = DateEdit(self.centralwidget)
        self.DateEdit.setGeometry(QtCore.QRect(310, 240, 172, 33))
        self.DateEdit.setObjectName("DateEdit")
        self.ProgressRing = ProgressRing(self.centralwidget)
        self.ProgressRing.setGeometry(QtCore.QRect(180, 400, 100, 100))
        self.ProgressRing.setObjectName("ProgressRing")
        self.PushButton = PushButton(self.centralwidget)
        self.PushButton.setGeometry(QtCore.QRect(50, 160, 102, 32))
        self.PushButton.setObjectName("PushButton")
        self.PushButton_2 = PushButton(self.centralwidget)
        self.PushButton_2.setGeometry(QtCore.QRect(160, 160, 102, 32))
        self.PushButton_2.setObjectName("PushButton_2")
        self.HyperlinkButton = HyperlinkButton(self.centralwidget)
        self.HyperlinkButton.setGeometry(QtCore.QRect(190, 80, 128, 31))
        self.HyperlinkButton.setObjectName("HyperlinkButton")
        self.CheckBox = CheckBox(self.centralwidget)
        self.CheckBox.setGeometry(QtCore.QRect(110, 250, 92, 22))
        self.CheckBox.setObjectName("CheckBox")
        self.ComboBox = ComboBox(self.centralwidget)
        self.ComboBox.setGeometry(QtCore.QRect(420, 110, 76, 32))
        self.ComboBox.setObjectName("ComboBox")
        self.HyperlinkButton_2 = HyperlinkButton(self.centralwidget)
        self.HyperlinkButton_2.setGeometry(QtCore.QRect(30, 330, 128, 31))
        self.HyperlinkButton_2.setObjectName("HyperlinkButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PushButton.setText(_translate("MainWindow", "Push button"))
        self.PushButton_2.setText(_translate("MainWindow", "Push button"))
        self.HyperlinkButton.setText(_translate("MainWindow", "Hyperlink button"))
        self.CheckBox.setText(_translate("MainWindow", "Check box"))
        self.HyperlinkButton_2.setText(_translate("MainWindow", "Hyperlink button"))
from qfluentwidgets import CheckBox, ComboBox, DateEdit, HyperlinkButton, ProgressRing, PushButton, ZhDatePicker
