# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(533, 376)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Labelchinese = QtWidgets.QLabel(self.groupBox)
        self.Labelchinese.setObjectName("Labelchinese")
        self.gridLayout.addWidget(self.Labelchinese, 0, 0, 1, 1)
        self.chinese = QtWidgets.QSpinBox(self.groupBox)
        self.chinese.setObjectName("chinese")
        self.gridLayout.addWidget(self.chinese, 0, 1, 1, 1)
        self.Labelmath = QtWidgets.QLabel(self.groupBox)
        self.Labelmath.setObjectName("Labelmath")
        self.gridLayout.addWidget(self.Labelmath, 1, 0, 1, 1)
        self.math = QtWidgets.QSpinBox(self.groupBox)
        self.math.setObjectName("math")
        self.gridLayout.addWidget(self.math, 1, 1, 1, 1)
        self.Labelenglish = QtWidgets.QLabel(self.groupBox)
        self.Labelenglish.setObjectName("Labelenglish")
        self.gridLayout.addWidget(self.Labelenglish, 2, 0, 1, 1)
        self.english = QtWidgets.QSpinBox(self.groupBox)
        self.english.setObjectName("english")
        self.gridLayout.addWidget(self.english, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 221, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Labeltotal = QtWidgets.QLabel(self.layoutWidget)
        self.Labeltotal.setObjectName("Labeltotal")
        self.gridLayout_2.addWidget(self.Labeltotal, 0, 0, 1, 1)
        self.total = QtWidgets.QLineEdit(self.layoutWidget)
        self.total.setObjectName("total")
        self.gridLayout_2.addWidget(self.total, 0, 1, 1, 1)
        self.Labelaverage = QtWidgets.QLabel(self.layoutWidget)
        self.Labelaverage.setObjectName("Labelaverage")
        self.gridLayout_2.addWidget(self.Labelaverage, 1, 0, 1, 1)
        self.average = QtWidgets.QLineEdit(self.layoutWidget)
        self.average.setObjectName("average")
        self.gridLayout_2.addWidget(self.average, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnCalculate = QtWidgets.QPushButton(self.groupBox)
        self.btnCalculate.setObjectName("btnCalculate")
        self.horizontalLayout_3.addWidget(self.btnCalculate)
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_3.addWidget(self.btnSave)
        self.btnClose = QtWidgets.QPushButton(self.groupBox)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_3.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        self.btnClose.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "学生成绩"))
        self.Labelchinese.setText(_translate("Form", "语文"))
        self.Labelmath.setText(_translate("Form", "数学"))
        self.Labelenglish.setText(_translate("Form", "英语"))
        self.groupBox_2.setTitle(_translate("Form", "成绩统计"))
        self.Labeltotal.setText(_translate("Form", "总成绩"))
        self.Labelaverage.setText(_translate("Form", "平均分"))
        self.btnCalculate.setText(_translate("Form", "计算"))
        self.btnSave.setText(_translate("Form", "保存"))
        self.btnClose.setText(_translate("Form", "关闭"))
