# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(484, 297)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.chinese = QtWidgets.QLabel(self.groupBox)
        self.chinese.setGeometry(QtCore.QRect(10, 22, 24, 16))
        self.chinese.setObjectName("chinese")
        self.math = QtWidgets.QLabel(self.groupBox)
        self.math.setGeometry(QtCore.QRect(10, 73, 24, 16))
        self.math.setObjectName("math")
        self.english = QtWidgets.QLabel(self.groupBox)
        self.english.setGeometry(QtCore.QRect(10, 125, 24, 16))
        self.english.setObjectName("english")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(50, 20, 124, 19))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setGeometry(QtCore.QRect(50, 70, 124, 19))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setGeometry(QtCore.QRect(50, 130, 124, 19))
        self.spinBox_3.setObjectName("spinBox_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 10, 230, 187))
        self.groupBox_2.setObjectName("groupBox_2")
        self.total = QtWidgets.QLabel(self.groupBox_2)
        self.total.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.total.setObjectName("total")
        self.average = QtWidgets.QLabel(self.groupBox_2)
        self.average.setGeometry(QtCore.QRect(20, 100, 54, 12))
        self.average.setObjectName("average")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 100, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.btnCalculate = QtWidgets.QPushButton(self.groupBox)
        self.btnCalculate.setGeometry(QtCore.QRect(80, 200, 75, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setGeometry(QtCore.QRect(260, 200, 75, 23))
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "学生成绩"))
        self.chinese.setText(_translate("Form", "语文"))
        self.math.setText(_translate("Form", "数学"))
        self.english.setText(_translate("Form", "英语"))
        self.groupBox_2.setTitle(_translate("Form", "成绩统计"))
        self.total.setText(_translate("Form", "总成绩"))
        self.average.setText(_translate("Form", "平均分"))
        self.btnCalculate.setText(_translate("Form", "计算"))
        self.btnSave.setText(_translate("Form", "保存"))
