# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buttom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import PushButton, SpinBox
from view.rotatetaichi import Taichi
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.PushButton = PushButton(Form)
        self.PushButton.setGeometry(QtCore.QRect(60, 110, 102, 32))
        self.PushButton.setObjectName("PushButton")
        self.SpinBox = SpinBox(Form)
        self.SpinBox.setGeometry(QtCore.QRect(230, 110, 113, 33))
        self.SpinBox.setObjectName("SpinBox")
        self.SpinBox.setValue(15)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.PushButton.clicked.connect(self.displaySpinBoxValue)
        self.PushButton.clicked.connect(self.openNewWindow)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PushButton.setText(_translate("Form", "绘制太极"))
    def displaySpinBoxValue(self):
        value = self.SpinBox.value()  # 获取SpinBox的值
        print(value)  # 在控制台打印SpinBox的值（你可以根据需求进行相应操作）
    def openNewWindow(self):
        self.new_window = Taichi(self.SpinBox.value())
        self.new_window.show()